/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.felixchristy.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FAQ service. Represents a row in the &quot;FAQ_FAQ&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.felixchristy.service.model.impl.FAQModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.felixchristy.service.model.impl.FAQImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FAQ
 * @see com.felixchristy.service.model.impl.FAQImpl
 * @see com.felixchristy.service.model.impl.FAQModelImpl
 * @generated
 */
public interface FAQModel extends BaseModel<FAQ> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a f a q model instance should use the {@link FAQ} interface instead.
	 */

	/**
	 * Returns the primary key of this f a q.
	 *
	 * @return the primary key of this f a q
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this f a q.
	 *
	 * @param primaryKey the primary key of this f a q
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the faq ID of this f a q.
	 *
	 * @return the faq ID of this f a q
	 */
	public long getFaqId();

	/**
	 * Sets the faq ID of this f a q.
	 *
	 * @param faqId the faq ID of this f a q
	 */
	public void setFaqId(long faqId);

	/**
	 * Returns the question of this f a q.
	 *
	 * @return the question of this f a q
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this f a q.
	 *
	 * @param question the question of this f a q
	 */
	public void setQuestion(String question);

	/**
	 * Returns the answer of this f a q.
	 *
	 * @return the answer of this f a q
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this f a q.
	 *
	 * @param answer the answer of this f a q
	 */
	public void setAnswer(String answer);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FAQ faq);

	public int hashCode();

	public CacheModel<FAQ> toCacheModel();

	public FAQ toEscapedModel();

	public String toString();

	public String toXmlString();
}